name: Water Reminder

on:
  schedule:
    - cron: '30 3,4,5,6,7,8,9,10,11,13 * * *'
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Send water reminder
        run: python send_water_reminder.py
        env:
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_MESSAGE: "Time to drink water! Stay hydrated."
          PUSHOVER_TITLE: "Water Reminder"
